#!/usr/bin/env python3
"""Builds src/lib/i18n/dict/{es,de,ar}.ts from scripts/i18n/tr*.py and lists keys still missing."""
import json, re, glob, importlib.util, pathlib
HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent.parent
rows = []
for f in sorted(glob.glob(str(HERE / "tr*.py"))):
    spec = importlib.util.spec_from_file_location(pathlib.Path(f).stem, f)
    m = importlib.util.module_from_spec(spec); spec.loader.exec_module(m)
    rows += m.TR
seen = {}
for r in rows:
    assert len(r) == 4, r
    en = r[0]
    ph = set(re.findall(r"\{\w+\}", en))
    for tr in r[1:]:
        assert set(re.findall(r"\{\w+\}", tr)) == ph, f"placeholder mismatch: {r}"
    seen[en] = r
for i, lang in enumerate(["es", "de", "ar"], 1):
    body = "".join(f"  {json.dumps(en, ensure_ascii=False)}: {json.dumps(r[i], ensure_ascii=False)},\n" for en, r in sorted(seen.items()))
    (ROOT / f"src/lib/i18n/dict/{lang}.ts").write_text(
        f"// Generated by scripts/i18n/build.py from scripts/i18n/tr*.py – edit those files, not this one.\n"
        f"const dict: Record<string, string> = {{\n{body}}};\n\nexport default dict;\n", encoding="utf8")
keys = json.load(open(ROOT / "scripts/i18n/keys.json"))
missing = [k for k in keys if k not in seen]
print(len(seen), "translated;", len(missing), "keys without translation (fall back to English)")
for k in missing: print("  missing:", k[:80])
