// Generates supabase/seed.sql from the demo data: npm run db:seed-sql
// Deterministic UUIDs (md5 of the demo id), so the seed can be re-run without duplicates.
import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";
import { DEMO_CATALOGS, DEMO_CLINICS } from "../src/lib/demo/clinics";

const uuid = (s: string) => {
  const h = createHash("md5").update(`aibooking-clinic:${s}`).digest("hex");
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-4${h.slice(13, 16)}-a${h.slice(17, 20)}-${h.slice(20, 32)}`;
};
const q = (v: unknown) => (v === null || v === undefined ? "null" : typeof v === "number" || typeof v === "boolean" ? String(v) : `'${String(v).replace(/'/g, "''")}'`);
const j = (v: unknown) => `${q(JSON.stringify(v))}::jsonb`;
const arr = (a: string[]) => `array[${a.map(q).join(",")}]::text[]`;
const uarr = (a: string[]) => `array[${a.map((x) => q(uuid(x))).join(",")}]::uuid[]`;

// All tables live in the "clinic" schema (see 0001_init.sql), so the seed never touches "public".
const out: string[] = ["-- Generated by scripts/generate-seed.ts – do not edit by hand.", "begin;", "set local search_path to clinic;"];
for (const c of DEMO_CLINICS) {
  const id = uuid(c.id);
  out.push(
    `insert into clinics (id, slug, name, tagline, description, type, emoji, accent_color, hero_image, address, city, phone, email, parking, insurance, review_url)
values (${[id, c.slug, c.name, c.tagline, c.description, c.type, c.emoji, c.accentColor, c.heroImage, c.address, c.city, c.phone, c.email, c.parking, c.insurance ?? "", c.reviewUrl ?? ""].map(q).join(", ")})
on conflict (id) do update set name = excluded.name, tagline = excluded.tagline, description = excluded.description;`,
    `insert into clinic_settings (clinic_id, opening_hours, booking, payment_methods, faq)
values (${q(id)}, ${j(c.openingHours)}, ${j(c.booking)}, ${arr(c.paymentMethods)}, ${j(c.faq)})
on conflict (clinic_id) do nothing;`,
    `insert into ai_agents (clinic_id, theme, accent_color, welcome_message, position, enabled)
values (${q(id)}, ${q(c.widget.theme)}, ${q(c.widget.accentColor)}, ${q(c.widget.welcomeMessage)}, ${q(c.widget.position)}, ${c.widget.enabled})
on conflict (clinic_id) do nothing;`,
    `insert into integrations (clinic_id, kind, enabled) values (${q(id)}, 'aibooking_calendar', true) on conflict do nothing;`,
  );
  const cat = DEMO_CATALOGS[c.id];
  for (const k of cat.categories)
    out.push(`insert into service_categories (id, clinic_id, name, emoji, sort_order) values (${[uuid(k.id), id, k.name, k.emoji, k.sortOrder].map(q).join(", ")}) on conflict (id) do nothing;`);
  cat.practitioners.forEach((p, i) =>
    out.push(
      `insert into practitioners (id, clinic_id, name, title, bio, color, work_days, active, sort_order) values (${[uuid(p.id), id, p.name, p.title, p.bio, p.color].map(q).join(", ")}, array[${p.workDays.join(",")}]::smallint[], ${p.active}, ${i}) on conflict (id) do nothing;`,
    ),
  );
  cat.services.forEach((s, i) =>
    out.push(
      `insert into services (id, clinic_id, category_id, name, description, duration_minutes, price, price_from, emoji, aliases, popular, new_clients_only, available, practitioner_ids, sort_order)
values (${[uuid(s.id), id, uuid(s.categoryId), s.name, s.description, s.durationMinutes, s.price, !!s.priceFrom, s.emoji].map(q).join(", ")}, ${arr(s.aliases ?? [])}, ${!!s.popular}, ${!!s.newClientsOnly}, true, ${uarr(s.practitionerIds)}, ${i})
on conflict (id) do nothing;`,
    ),
  );
}
out.push("commit;");
writeFileSync("supabase/seed.sql", out.join("\n") + "\n");
console.log(`Wrote supabase/seed.sql (${out.length} statements)`);
